#!/bin/bash
# /usr/bin/blurlock

# take screenshot
import -window root /tmp/screenshot.jpeg

# blur it
convert /tmp/screenshot.jpeg -scale 10% -blur 0x2 -quality 21 -resize 1000% /tmp/screenshotblur.png
rm /tmp/screenshot.jpeg

# lock the screen
i3lock -i /tmp/screenshotblur.png

# sleep 1 adds a small delay to prevent possible race conditions with suspend

exit 0
