#!/bin/bash

layouts="$(find /home/benny/.screenlayout -maxdepth 1 -type f -printf '%f\n')"

# Get user choice including multi-monitor and manual selection:
chosen=$(printf "$layouts" | dmenu -i -p "Select display layout:") &&

bash $chosen

#setbg		# Fix background if screen size/arangement has changed.
#remaps		# Re-remap keys if keyboard added (for laptop bases)
#pgrep -x dunst >/dev/null && killall dunst && setsid dunst & # Restart dunst to ensure proper location on screen