#!/bin/bash

BRIGHTNESS=`xrandr --verbose | grep -m 1 -i brightness | cut -f2 -d ' '`
MINVALUE=0.0
MAXVALUE=1.0

if [ "$(echo "if (${BRIGHTNESS} < ${MAXVALUE}) 1" | bc)" -eq 1 ] && [ $1 == "inc" ];
then
        SETVALUE=$(echo "$BRIGHTNESS+0.05" | bc)
fi

if [ "$(echo "if (${BRIGHTNESS} > ${MINVALUE}) 1" | bc)" -eq 1 ] && [ $1 == "dec" ];
then
        SETVALUE=$(echo "$BRIGHTNESS-0.05" | bc)
fi


xrandr --output eDP-1 --brightness $SETVALUE
xrandr --output eDP-1-1 --brightness $SETVALUE
xrandr --output eDP1 --brightness $SETVALUE